# Generated by Django 5.1.3 on 2024-11-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.BigIntegerField(default=1, unique=True)),
                ('name', models.CharField(max_length=5000)),
            ],
        ),
    ]
