# Generated by Django 5.1.3 on 2024-12-02 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_note_on_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamenote',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
