# Generated by Django 5.1.3 on 2024-12-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_note_on_site', '0002_alter_gamenote_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenote',
            name='hours',
            field=models.IntegerField(null=True),
        ),
    ]
