# Generated by Django 5.1.3 on 2024-12-05 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_note_on_site', '0004_alter_gamenote_score'),
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenote',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_notes', to='my_auth.profile'),
        ),
    ]
