# Generated by Django 5.1.3 on 2024-12-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_note_on_site', '0005_gamenote_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenote',
            name='optional_notes',
            field=models.TextField(null=True),
        ),
    ]
