# Generated by Django 5.1.3 on 2024-12-25 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_note_on_site', '0006_gamenote_optional_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamenote',
            name='optional_notes',
        ),
    ]
